export const homeBodyHtml = `<p>This is a specialized website designed to cater to the needs of professionals in the web development and technology sector by offering a unique and innovative service, generating badges for various web development technologies. This platform is particularly valuable for developers, IT professionals, and digital designers seeking to visually showcase their technical skills and expertise.</p>
<p>Key Features:</p>
<p>1. Comprehensive Badge Collection: We provides a vast array of badges representing a wide range of web development technologies, programming languages, frameworks, and tools. This includes popular technologies like HTML5, CSS3, JavaScript, as well as frameworks like React, Vue.js, and Angular, among others.</p>
<p>2. User-Friendly Interface: The website is designed with a focus on user experience, featuring a clean, intuitive interface that makes navigating through the badge creation process simple and efficient. Users can easily find and select the technologies they are proficient in.</p>
<p>3. Customization and Flexibility: Users can customize their badges according to their preferences. This includes options for different sizes, styles, and layouts, allowing for a personalized touch that can align with individual or corporate branding.</p>
<p>4. Seamless Integration and Download: After creating their desired badges, users have the option to download them in various formats suitable for both web and print use. Additionally, Badges.bio provides embeddable code snippets in HTML and Markdown, making it easy to integrate the badges into websites, portfolios, and GitHub READMEs.</p>
<p>How to show README in Github profile? To show it on the front page of your profile, create a repo, named exactly the same as your account name, add, commit and push an updated README</p>
<p>5. Responsive Design: The website is built with a responsive design, ensuring a seamless and consistent experience across various devices and screen sizes, from desktops to mobile phones.</p>
<p>6. Community Engagement: Badges.bio encourages a sense of community among its users. The platform may offer features like a gallery or a showcase section where users can display their badge collections and view others' arrangements for inspiration. Join our telegram!</p>
<p>7. Resource Hub: Apart from being a badge generator, in future, we can also serve as a resource hub, offering blog posts, articles, or updates on the latest trends and developments in the web development field.</p>
<p>8. Feedback and Continuous Improvement: The website likely includes a mechanism for users to provide feedback, ensuring that the service remains relevant, user-friendly, and up-to-date with the latest technological advancements.</p>
<p>Badges.bio stands out as a practical and innovative solution for tech professionals to visually represent their skills and keep up with the dynamic world of web development. It serves not just as a tool for creating badges, but also as a platform for learning, inspiration, and professional growth in the tech community.</p>
`;
